services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=petanquedb'
      - 'POSTGRES_PASSWORD=K-ro'
      - 'POSTGRES_USER=petanque_usr'
    ports:
      - '5432:5432'

  petanque:
    build: .
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petanquedb'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", 'http://petanque:8080/actuator/health']
      interval: 1s
      timeout: 2s
      retries: 50

  data:
    image: jetbrains/intellij-http-client
    depends_on:
      petanque:
        condition: service_healthy
    command:
      - '-D'
      - 'http/init.http'
    volumes:
      - ./http:/workdir/http/
