services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=petanquedb'
      - 'POSTGRES_PASSWORD=K-ro'
      - 'POSTGRES_USER=petanque_usr'
    ports:
      - '5432:5432'
