spring:
  application:
    name: petanque
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/petanquedb'
    username: petanque_usr
    password: K-ro
server:
  error:
    include-stacktrace: never
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /petanque.openapi.yaml