# Petanque


###
# @name Add Season
POST http://{{host}}:{{port}}/seasons

###
# @name Add Player
POST http://{{host}}:{{port}}/players
Content-Type: application/json

{
  "name": "Olivier"
}

###
# @name Add Player
POST http://{{host}}:{{port}}/players
Content-Type: application/json

{
  "name": "John"
}

###
# @name Add Game
POST http://{{host}}:{{port}}/games
Content-Type: application/json

{
  "winners": [
    "Olivier"
  ],
  "losers": [
    "John"
  ],
  "losersScore": 5
}

###
# @name Add Game
POST http://{{host}}:{{port}}/games
Content-Type: application/json

{
  "winners": [
    "Olivier"
  ],
  "losers": [
    "John"
  ],
  "losersScore": 5
}

###
# @name Add Game
POST http://{{host}}:{{port}}/games
Content-Type: application/json

{
  "winners": [
    "John"
  ],
  "losers": [
    "Olivier"
  ],
  "losersScore": 5
}

