# Petanque

###
# @name Add Season
POST http://{{host}}:{{port}}/seasons

###
# @name Add Player
POST http://{{host}}:{{port}}/players
Content-Type: application/json

{
  "name": "Olivier"
}

###
# @name Get players
GET http://{{host}}:{{port}}/players

###
# @name Get player
GET http://{{host}}:{{port}}/players/John

###
# @name Get games for player
GET http://{{host}}:{{port}}/players/John/games

###
# @name Add Game
POST http://{{host}}:{{port}}/games
Content-Type: application/json

{
  "winners": [
    "Olivier"
  ],
  "losers": [
    "John"
  ],
  "losersScore": 5
}

###
# @name Get Games
GET http://{{host}}:{{port}}/games

###
# @name Delete last game
DELETE http://{{host}}:{{port}}/games

###
# @name Get current season
GET http://{{host}}:{{port}}/seasons/current

###
# @name Get all seasons
GET http://{{host}}:{{port}}/seasons
