# Petanque

###
# @name Add Player
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "PES"
}

###
# @name Get players
GET http://localhost:8080/players

###
# @name Get Games
GET http://localhost:8080/games

###
# @name Add Game
POST http://localhost:8080/games
Content-Type: application/json

{
  "winners": [
    "olivier",
    "jon"
  ],
  "losers": [
    "tim",
    "garrett"
  ],
  "losersScore": 2
}

###
# @name Add Season
POST http://localhost:8080/seasons

###
# @name Get current season
GET http://localhost:8080/seasons/current